"""Initial migration

Revision ID: ee28b0a06f31
Revises: 
Create Date: 2026-01-22 01:32:13.029030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.db_types


# revision identifiers, used by Alembic.
revision: str = 'ee28b0a06f31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('coverage_grid',
    sa.Column('user_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('time_bucket', sa.String(), nullable=False),
    sa.Column('topic_bucket', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'time_bucket', 'topic_bucket')
    )
    op.create_table('threads',
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('user_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('root_prompt', sa.Text(), nullable=False),
    sa.Column('persona', sa.String(), nullable=False),
    sa.Column('time_focus', sa.JSON(), nullable=True),
    sa.Column('topic_focus', sa.JSON(), nullable=True),
    sa.Column('questions_asked', sa.Integer(), nullable=False),
    sa.Column('questions_since_last_freeform', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('year_of_birth', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('primary_language', sa.String(), nullable=True),
    sa.Column('relationship_status', sa.String(), nullable=True),
    sa.Column('has_children', sa.Boolean(), nullable=True),
    sa.Column('children_count', sa.Integer(), nullable=True),
    sa.Column('children_age_brackets', sa.JSON(), nullable=True),
    sa.Column('main_role', sa.String(), nullable=True),
    sa.Column('field_or_industry', sa.String(), nullable=True),
    sa.Column('avoid_topics', sa.JSON(), nullable=True),
    sa.Column('intensity', sa.String(), nullable=True),
    sa.Column('life_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('questions',
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('thread_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('index_in_thread', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('time_focus', sa.JSON(), nullable=True),
    sa.Column('topic_focus', sa.JSON(), nullable=True),
    sa.Column('requires_children', sa.Boolean(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread_freeforms',
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('thread_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('index_in_thread', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('life_entries',
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('user_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('thread_id', app.core.db_types.GUID(), nullable=True),
    sa.Column('source_question_id', app.core.db_types.GUID(), nullable=True),
    sa.Column('time_bucket', sa.String(), nullable=False),
    sa.Column('approx_year_start', sa.Integer(), nullable=True),
    sa.Column('approx_year_end', sa.Integer(), nullable=True),
    sa.Column('timeframe_label', sa.String(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('distilled', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('topic_buckets', sa.JSON(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('seal_type', sa.String(), nullable=False),
    sa.Column('seal_release_at', sa.DateTime(), nullable=True),
    sa.Column('seal_event_key', sa.String(), nullable=True),
    sa.Column('seal_audiences_blocked', sa.JSON(), nullable=True),
    sa.Column('emotional_tone', sa.String(), nullable=True),
    sa.Column('people', sa.JSON(), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('question_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('user_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('choice_id', sa.String(), nullable=True),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('linked_entry_id', app.core.db_types.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['linked_entry_id'], ['life_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('life_entries')
    op.drop_table('thread_freeforms')
    op.drop_table('questions')
    op.drop_table('user_profiles')
    op.drop_table('threads')
    op.drop_table('coverage_grid')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
